Repository LUXROBO/pymodi, pull requests merged in 2021-04, with the labels that each got.

#429 Feature/gui firmware updater
  modi/util/gui_firmware_updater.py
Labels: size/M

#430 Feature/gui firmware updater
  modi/assets/modi_firmware_updater.ui
  modi/util/gui_firmware_updater.py
Labels: size/L

#431 Feature/gui firmware updater
  modi/assets/modi_firmware_updater.ui
  modi/util/gui_firmware_updater.py
Labels: size/M

#432 Refactor GUI in feature/gui-firmware-updater
  modi/assets/modi_firmware_updater.ui
  modi/util/firmware_updater.py
  modi/util/gui_firmware_updater.py
Labels: size/L

#433 Implement feature/gui-firmware-updater
  modi/assets/modi_firmware_updater.ui
  modi/util/firmware_updater.py
  modi/util/gui_firmware_updater.py
Labels: size/XL

#434 Fix UI and url for Windows
  modi/assets/modi_firmware_updater.ui
  modi/util/gui_firmware_updater.py
Labels: size/M

#435 Fix network module initializing error
  modi/assets/modi_firmware_updater.ui
  modi/util/firmware_updater.py
  modi/util/gui_firmware_updater.py
Labels: size/L
